{
 "title": "Benchmarking private 5G",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "experiment" },
   {
    "name": "experiment_name",
    "label": "Experiment name",
    "query": "sensor_continuous_low_bw_long_dur_low_pl_analysis, cbr_low_bw_med_dur_low_pl_analysis, cbr_med_bw_med_dur_low_pl_analysis, cbr_high_bw_low_dur_low_pl_analysis, cbr_vhigh_bw_low_dur_low_pl_analysis, cbr_xhigh_bw_vlow_dur_low_pl_analysis, sensor_continuous_low_bw_xlong_dur_low_pl_analysis"
   }
  ]
 },
 "panels": [
  {
   "title": "Time range test",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"5gbenchmarking\")\n  |> range(start: -10d) |> filter(fn: (r) => r._measurement == \"${experiment_name}\" and r._field == \"packet_interarrival_time\") |> keep(columns: [\"_time\", \"_value\"]) |> limit(n: 7500)"
    }
   ]
  },
  {
   "title": "Packet interarrival time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"5gbenchmarking\")\n  |> range(start: -10d) |> filter(fn: (r) => r._measurement == \"${experiment}\" and r._field == \"packet_interarrival_time\") |> keep(columns: [\"_time\", \"_value\"]) |> aggregateWindow(every:350ms, fn:mean, createEmpty:false)\n"
    }
   ]
  },
  { "title": "One-Way Delay", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Packet OWD",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 17 },
   "targets": [
    {
     "query": "from(bucket: \"5gbenchmarking\")\n  |> range(start: -20d) |> filter(fn: (r) => r._measurement == \"${experiment}\" and r._field == \"packet_owd\") |> keep(columns: [\"_time\", \"_value\"]) |> aggregateWindow(every:350ms, fn:mean, createEmpty:false)\n"
    }
   ]
  },
  {
   "title": "CDF - Packet owd",
   "type": "sebastiangunreben-cdf-panel",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "query": "from(bucket: \"5gbenchmarking\")\r\n  |> range(start: -10d) |> filter(fn: (r) => r._measurement == \"${experiment}\" and r._field == \"packet_owd\") |> keep(columns: [\"_time\", \"_value\"]) |> aggregateWindow(every:350ms, fn:mean, createEmpty:false)\r\n"
    }
   ]
  },
  { "title": "Inter-Packet Delay Variation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Packet Jitter",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 26 },
   "targets": [
    {
     "query": "from(bucket: \"5gbenchmarking\")\r\n  |> range(start: -20d) |> filter(fn: (r) => r._measurement == \"${experiment}\") |> filter(fn: (r) => r._field == \"packet_jitter\") |> aggregateWindow(every:350ms, fn:mean, createEmpty:false)"
    }
   ]
  },
  {
   "title": "CDF - Packet jitter",
   "type": "sebastiangunreben-cdf-panel",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "query": "from(bucket: \"5gbenchmarking\")\r\n  |> range(start: -10d) |> filter(fn: (r) => r._measurement == \"${experiment}\" and r._field == \"packet_jitter\") |> keep(columns: [\"_time\", \"_value\"]) |> aggregateWindow(every:350ms, fn:mean, createEmpty:false)\r\n"
    }
   ]
  },
  { "title": "Inter-Arrival Time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Packet Interarrival time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "query": "from(bucket: \"5gbenchmarking\")\r\n  |> range(start: -10d) |> filter(fn: (r) => r._measurement == \"${experiment}\") |> filter(fn: (r) => r._field == \"packet_interarrival_time\") |> aggregateWindow(every:350ms, fn:mean, createEmpty:false)"
    }
   ]
  },
  {
   "title": "CDF - Packet interarrival time",
   "type": "sebastiangunreben-cdf-panel",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "query": "from(bucket: \"5gbenchmarking\")\r\n  |> range(start: -10) |> filter(fn: (r) => r._measurement == \"${experiment}\" and r._field == \"packet_interarrival_time\") |> keep(columns: [\"_time\", \"_value\"]) |> aggregateWindow(every:350ms, fn:mean, createEmpty:false)\r\n"
    }
   ]
  },
  {
   "title": "Inter arrival time distribution",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "query": "from(bucket: \"5gbenchmarking\")\n  |> range(start: -10d) |> filter(fn: (r) => r._measurement == \"${experiment}\" and r._field == \"packet_interarrival_time\") |> keep(columns: [\"_time\", \"_value\"]) |> aggregateWindow(every:350ms, fn:mean, createEmpty:false)\n"
    }
   ]
  },
  { "title": "Aggregate KPIs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Packet loss",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"5gbenchmarking\")\r\n  |> range(start: 0) |> filter(fn: (r) => r._measurement == \"${experiment}_aggregate\" and r._field == \"packet_loss\") |> keep(columns: [\"_time\", \"_value\"])\r\n"
    }
   ]
  },
  {
   "title": "Average Throughput",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"5gbenchmarking\")\r\n  |> range(start: 0) |> filter(fn: (r) => r._measurement == \"${experiment}_aggregate\" and r._field == \"throughput\") |> keep(columns: [\"_time\", \"_value\"])\r\n"
    }
   ]
  },
  {
   "title": "Aggregate measurements",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "query": "from(bucket: \"5gbenchmarking\")\r\n  |> range(start: 0) |> filter(fn: (r) => r._measurement == \"${experiment}_aggregate\" and r._field =~ /availability_/) |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")"
    }
   ]
  }
 ]
}