---
# Run with ansible-playbook playbook_name.yml --extra-vars "@file_path_to_vars_file"
- name: Validate bridge
  become: true
  hosts: localhost

  tasks:
    - name: Start tshark ingres
      become: yes
      shell: "tshark -i enp5s0 -f 'udp port 8000' -a duration:60 -w /opt/hallo/output_files/pcaps/validate_bridge_ingres.pcapng"
      async: "{{ (60+10)|int|abs }}"
      poll: 0
      register: tshark_ingres

    - name: Start tshark egres
      become: yes
      shell: "tshark -i enp3s0 -f 'udp port 8000' -a duration:60 -w /opt/hallo/output_files/pcaps/validate_bridge_egres.pcapng"
      async: "{{ (60+10)|int|abs }}"
      poll: 0
      register: tshark_egres

    - name: Generate traffic
      become: yes
      async: "{{ (60+10)|int|abs }}" 
      poll: 0 # start the task in the background and move on to the next task without waiting for completion
      shell: python3 /opt/trex/v3.04/automation/trex_control_plane/interactive/trex/examples/stl/my-automation-test.py -m {{ pps }}pps -d 60 --payload_size 16
      register: traffgen_output
      delegate_to: 129.241.200.231


    - name: Wait for tshark ingres to complete
      async_status:
        jid: "{{ tshark_ingres.ansible_job_id }}"
      register: tshark_ingres_result
      until: tshark_ingres_result.finished
      retries: 15
      delay: 10

    - name: Wait for tshark egres to complete
      async_status:
        jid: "{{ tshark_egres.ansible_job_id }}"
      register: tshark_egres_result
      until: tshark_egres_result.finished
      retries: 15
      delay: 10

    - name: Count packets ingres
      become: yes
      shell: tshark -r /opt/hallo/output_files/pcaps/validate_bridge_ingres.pcapng | wc -l
      register: number_of_packets_ingres
      when: tshark_ingres_result.finished

    - name: Count packets egres
      become: yes
      shell: tshark -r /opt/hallo/output_files/pcaps/validate_bridge_egres.pcapng | wc -l
      register: number_of_packets_egres
      when: tshark_egres_result.finished

    - name: Append packet count to CSV file
      lineinfile:
        path: /home/shared/validation_backups/sensitivity_analysis_bridge/results_16.csv
        line: "{{ pps }}, {{ number_of_packets_ingres.stdout }}, {{ number_of_packets_egres.stdout }}"
        create: yes
      become: true